apps/core/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView, TemplateView

app_name = 'core'

urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('game:statistics'), permanent=False), name='home'),
    path('terms-and-conditions/', TemplateView.as_view(template_name="core/terms_and_conditions.html"),
         name='terms-and-conditions'),
]

apps/user/urls.py
from django.urls import path

from .views import profile_view, SignOutView, sign_in_view, sign_up_view

app_name = 'user'

urlpatterns = [
    path('profile/', profile_view, name='profile'),
    path('sign-out/', SignOutView.as_view(), name='sign-out'),
    path('sign-in/', sign_in_view, name='sign-in'),
    path('sign-up/', sign_up_view, name='sign-up'),
]

main_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.core.urls')),
    path('game/', include('apps.game.urls')),
    path('user/', include('apps.user.urls')),
    path('admin/', admin.site.urls),
]

apps/user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    class Gender(models.TextChoices):
        MALE = 'M', _('Male')
        FEMALE = 'F', _('Female')
        NON_BINARY = 'N', _('Non-Binary')

    email = models.EmailField(  # This field needed to be replaced to make it 'unique = True'
        _('Email Address'),
        unique=True,
        error_messages={
            'unique': _("A user with that email already exists"),
        },
    )
    birthdate = models.DateField(
        _('Birthdate'),
        null=True
    )
    gender = models.CharField(
        _('Gender'),
        max_length=1,
        choices=Gender.choices,
        null=True
    )

apps/user/forms.py
from django import forms
from django.contrib.auth import get_user_model, authenticate
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext as _

from helpers.forms import DateInput

User = get_user_model()


class SingUpForm(forms.ModelForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput(), help_text=_('Please enter the password again'))
    email = forms.EmailField(required=True)
    birthdate = forms.DateField(required=True, widget=DateInput())
    gender = forms.ChoiceField(choices=User.Gender.choices, widget=forms.RadioSelect)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data['password']
        confirm_password = cleaned_data['confirm_password']
        if password != confirm_password:
            raise ValidationError(_('Password fields are not equal'))

        return cleaned_data

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password',
            'confirm_password',
            'birthdate',
            'gender',
        )


class SingInForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data['username']
        password = cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user:
            if not user.is_active:
                raise ValidationError(_('User is not active!'))
        else:
            raise ValidationError(_('Username or password is incorrect'))

        return cleaned_data


class ProfileForm(forms.ModelForm):
    username = forms.CharField(disabled=True, help_text=_('Username cannot be changed'))
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    birthdate = forms.DateField(required=True, widget=DateInput())
    gender = forms.ChoiceField(choices=User.Gender.choices, widget=forms.RadioSelect)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'birthdate',
            'gender',
        )


class ChangePasswordForm(forms.Form):
    current_password = forms.CharField(widget=forms.PasswordInput())
    new_password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput(), help_text=_('Please enter the new password again'))

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def clean_current_password(self):
        current_password = self.cleaned_data['current_password']
        if not self.user.check_password(current_password):
            raise ValidationError(_('Password is incorrect'))

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data['new_password']
        confirm_password = cleaned_data['confirm_password']
        if new_password != confirm_password:
            raise ValidationError(_('Password fields are not equal'))

        return cleaned_data

apps/user/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import logout, get_user_model, authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.utils.translation import ugettext as _
from django.views.generic import View

from .forms import SingInForm, SingUpForm, ProfileForm, ChangePasswordForm

User = get_user_model()


class SignOutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)

        if request.GET.get('next'):
            redirect_url = request.GET['next']
        else:
            redirect_url = settings.LOGOUT_REDIRECT_URL

        return HttpResponseRedirect(redirect_url)


def sign_up_view(request):
    form = SingUpForm()

    if request.method == 'POST':
        form = SingUpForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            user.set_password(user.password)
            user.save()
            login(request, user)
            return HttpResponseRedirect(settings.LOGIN_REDIRECT_URL)

    return render(request, 'user/sign_up.html', {'form': form})


def sign_in_view(request):
    form = SingInForm()

    if request.method == 'POST':
        form = SingInForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            login(request, user)

            if request.GET.get('next'):
                redirect_url = request.GET['next']
            else:
                redirect_url = settings.LOGIN_REDIRECT_URL

            return HttpResponseRedirect(redirect_url)

    return render(request, 'user/sign_in.html', {'form': form})


@login_required
def profile_view(request):
    user = request.user
    profile_form = ProfileForm(instance=user)
    change_password_form = ChangePasswordForm(user=user)

    if request.method == 'POST':
        form_type = request.POST.get('form_type')

        if form_type == 'profile':
            profile_form = ProfileForm(data=request.POST, instance=user)
            if profile_form.is_valid():
                profile_form.save()
                messages.success(request, _('Profile successfully updated'))

        elif form_type == 'change_password':
            change_password_form = ChangePasswordForm(user=user, data=request.POST)
            if change_password_form.is_valid():
                user.set_password(change_password_form.cleaned_data['new_password'])
                user.save()
                messages.success(request, _('Password successfully changed'))

    return render(
        request,
        'user/profile.html',
        {
            'profile_form': profile_form,
            'change_password_form': change_password_form
        }
    )

apps/user/templates/user/auth_base.html
{% extends 'core/base.html' %}
{% load static i18n %}

{% block content %}
    <div class="container">
        <h3 class="text-center text-danger fw-bold pb-5">{% trans "Who Wants to Be a Millionaire!" %}</h3>

        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item" role="presentation">
                        <a
                                class="nav-link {% if 'sign-up' in request.path %}active{% endif %}"
                                href="{% url 'user:sign-up' %}"
                                role="tab"
                        >
                            {% trans "Sign Up" %}
                        </a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a
                                class="nav-link {% if 'sign-in' in request.path %}active{% endif %}"
                                href="{% url 'user:sign-in' %}"
                                role="tab"
                        >
                            {% trans "Sign In" %}
                        </a>
                    </li>
                </ul>
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade pt-4 show active" role="tabpanel">
                        {% block tab_content %}{% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

apps/user/templates/user/profile.html
{% extends 'core/base.html' %}
{% load static i18n %}

{% block title %}{% trans "Profile" %}{% endblock %}

{% block content %}
    <div class="container">
        {% include 'core/_messages.html' with messages=messages %}

        <div class="row">
            <div class="col-xl-8 mb-4 d-flex align-items-stretch">
                <div class="card w-100">
                    <div class="card-body">
                        <form method="post" action="{% url 'user:profile' %}">
                            {{ profile_form.non_field_errors }}
                            {% csrf_token %}

                            {% for field in profile_form %}
                                {% include 'core/_input_horizontal.html' with field=field %}
                            {% endfor %}

                            <input type="hidden" name="form_type" value="profile">

                            <button type="submit" class="btn btn-danger">{% trans "Save" %}</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-xl-4 mb-4 d-flex align-items-stretch">
                <div class="card w-100">
                    <div class="card-body">
                        <h5 class="card-title text-danger">{% trans "Change Password" %}</h5>

                        <form method="post" action="{% url 'user:profile' %}">
                            {{ change_password_form.non_field_errors }}
                            {% csrf_token %}

                            {% for field in change_password_form %}
                                {% include 'core/_input_vertical.html' with field=field %}
                            {% endfor %}

                            <input type="hidden" name="form_type" value="change_password">

                            <button type="submit" class="btn btn-danger">{% trans "Change" %}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        id_birthdate.max = new Date().toISOString().split("T")[0];
    </script>
{% endblock %}

apps/user/templates/user/sign_in.html
{% extends 'user/auth_base.html' %}
{% load static widget_tweaks i18n %}

{% block title %}{% trans "Sign In" %}{% endblock %}

{% block tab_content %}
    <form
            method="post"
            action="{% url 'user:sign-in' %}{% if request.GET.next %}?next={{ request.GET.next }}{% endif %}"
    >
        {{ form.non_field_errors }}
        {% csrf_token %}

        {% for field in form %}
            {% include 'core/_input_horizontal.html' with field=field %}
        {% endfor %}

        <button type="submit" class="btn btn-danger">{% trans "Sign In" %}</button>
    </form>
{% endblock %}

apps/user/templates/user/sign_up.html
{% extends 'user/auth_base.html' %}
{% load static widget_tweaks i18n %}

{% block title %}{% trans "Sign Up" %}{% endblock %}

{% block tab_content %}
    <form method="post" action="{% url 'user:sign-up' %}">
        {{ form.non_field_errors }}
        {% csrf_token %}

        {% for field in form %}
            {% include 'core/_input_horizontal.html' with field=field %}
        {% endfor %}

        <p>
            {% trans "By signing up, you agree to our" %}
            <a href="{% url 'core:terms-and-conditions' %}">{% trans "Terms of Services" %}</a>
        </p>
        <button type="submit" class="btn btn-danger">{% trans "Sign Up" %}</button>
    </form>
{% endblock %}

{% block js %}
    <script>
        id_birthdate.max = new Date().toISOString().split("T")[0];
    </script>
{% endblock %}