apps/core/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView, TemplateView

app_name = 'core'

urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('game:statistics'), permanent=False), name='home'),
    path('terms-and-conditions/', TemplateView.as_view(template_name="core/terms_and_conditions.html"),
         name='terms-and-conditions'),
]

apps/user/urls.py
from django.urls import path

from .views import profile_view, SignOutView, sign_in_view, sign_up_view

app_name = 'user'

urlpatterns = [
    path('profile/', profile_view, name='profile'),
    path('sign-out/', SignOutView.as_view(), name='sign-out'),
    path('sign-in/', sign_in_view, name='sign-in'),
    path('sign-up/', sign_up_view, name='sign-up'),
]

main_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.core.urls')),
    path('game/', include('apps.game.urls')),
    path('user/', include('apps.user.urls')),
    path('admin/', admin.site.urls),
]

apps/core/templates/core/_input_horizontal.html
{% load widget_tweaks %}

<div class="row mb-3">
    {% if field.field.required %}
        {{ field|add_label_class:'col-lg-2 col-form-label required' }}
    {% else %}
        {{ field|add_label_class:'col-lg-2 col-form-label' }}
    {% endif %}

    <div class="col-lg-10">
        {% if field.field.widget.input_type == 'radio' %}
            {{ field|add_class:'radio-control' }}
            {{ field.errors }}
        {% else %}
            {{ field|add_class:'form-control'|add_error_class:'is-invalid' }}
            {% if field.help_text %}
                <div class="form-text">{{ field.help_text }}</div>{% endif %}
            {{ field.errors }}
        {% endif %}
    </div>
</div>

apps/core/templates/core/_input_vertical.html
{% load widget_tweaks %}

<div class="mb-3">
    {% if field.field.required %}
        {{ field|add_label_class:'form-label required' }}
    {% else %}
        {{ field|add_label_class:'form-label' }}
    {% endif %}

    {% if field.field.widget.input_type == 'radio' %}
        {{ field|add_class:'radio-control' }}
        {{ field.errors }}
    {% else %}
        {{ field|add_class:'form-control'|add_error_class:'is-invalid' }}
        {% if field.help_text %}
            <div class="form-text">{{ field.help_text }}</div>{% endif %}
        {{ field.errors }}
    {% endif %}
</div>

apps/core/templates/core/_messages.html
{% load custom %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.level_tag|bootstrap_level_tag_map }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

apps/core/templates/core/_navbar.html
{% load static i18n %}

<nav class="main-navbar navbar navbar-expand-lg navbar-light bg-light mb-5">
    <div class="container">
        <a class="navbar-brand text-danger fw-bold" href="{% url 'core:home' %}">
            <img class="pe-1" src="{% static 'core/images/logo.png' %}" alt="logo" width="30">
            {% trans "Millionaire" %}
        </a>
        <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:home' %}">
                        {% trans "Home" %}
                    </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a
                                class="nav-link dropdown-toggle"
                                href="#"
                                role="button"
                                data-bs-toggle="dropdown"
                        >
                            <i class="fa fa-user pe-1"></i>
                            {% if user.get_full_name %}
                                {{ user.get_full_name }}
                            {% else %}
                                {{ user.username }}
                            {% endif %}
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a class="dropdown-item" href="{% url 'user:profile' %}">
                                    {% trans "Profile" %}
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'user:sign-out' %}">
                                    {% trans "Sign Out" %}
                                </a>
                            </li>
                        </ul>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

apps/core/templates/core/base.html
{% load static i18n %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta
            name="viewport"
            content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    >
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '@fortawesome/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/forms.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">

    {% block css %}{% endblock %}

    <title>{% block title %}{% endblock %} | {% trans "Millionaire" %}</title>
</head>
<body class="pb-5">

{% include 'core/_navbar.html' %}

{% block content %}{% endblock %}

<script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>

{% block js %}{% endblock %}
</body>
</html>

apps/core/templates/core/terms_and_conditions.html
{% extends 'core/base.html' %}
{% load static i18n %}

{% block title %}{% trans "Terms and Conditions" %}{% endblock %}

{% block content %}
    <div class="container">
        <h3>1. General</h3>

        <p class="text-justify">
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
            industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and
            scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into
            electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of
            Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like
            Aldus PageMaker including versions of Lorem Ipsum.
        </p>

        <p class="text-justify">
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
            industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and
            Aldus PageMaker including versions of Lorem Ipsum.
        </p>

        <h3>2. Intellectual Property Rights</h3>

        <p class="text-justify">
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
            industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and
            scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
            industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and
            scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into
            electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of
            Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like
            Aldus PageMaker including versions of Lorem Ipsum.
        </p>

        <h3>3. Registration and Passwords </h3>

        <p class="text-justify">
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
            industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and
            electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of
            Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like
            Aldus PageMaker including versions of Lorem Ipsum.
        </p>

        <p class="text-justify">
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
            industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and
            scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into
            electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
            industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and
            scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into
            electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of
            Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like
            Aldus PageMaker including versions of Lorem Ipsum.
        </p>

        <h3>Use of Directories</h3>

        <p class="text-justify">
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
            industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and
            scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into
            electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of
            Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like
            Aldus PageMaker including versions of Lorem Ipsum.
        </p>

        <h3>Privacy Policy</h3>

        <p class="text-justify">
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
            electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of
            Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like
            Aldus PageMaker including versions of Lorem Ipsum.
        </p>

        <h3>Collection and Use</h3>

        <p class="text-justify">
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
            Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like
            Aldus PageMaker including versions of Lorem Ipsum.
        </p>

        <h3>Security</h3>

        <p class="text-justify">
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
            Aldus PageMaker including versions of Lorem Ipsum.
        </p>
    </div>
{% endblock %}